---
- name: Install OpenSSH Server on Windows
  hosts: windows
  gather_facts: false
  become: true
  become_method: runas
  become_user: SYSTEM

  tasks:
    - name: Check if OpenSSH Server is already installed
      ansible.windows.win_shell: |
        Get-WindowsCapability -Online | Where-Object Name -like 'OpenSSH.Server*'
      register: openssh_check
      changed_when: false

    - name: Display OpenSSH Server status
      ansible.builtin.debug:
        msg: "{{ openssh_check.stdout_lines }}"

    - name: Install OpenSSH Server
      ansible.windows.win_shell: |
        Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
      when: "'Installed' not in openssh_check.stdout"
      register: openssh_install

    - name: Display installation result
      ansible.builtin.debug:
        msg: "OpenSSH Server installed successfully"
      when: openssh_install.changed

    - name: Start and enable SSH service
      ansible.windows.win_service:
        name: sshd
        state: started
        start_mode: auto

    - name: Start and enable SSH Agent service
      ansible.windows.win_service:
        name: ssh-agent
        state: started
        start_mode: auto

    - name: Configure firewall rule for SSH
      ansible.windows.win_shell: |
        New-NetFirewallRule -Name sshd -DisplayName 'OpenSSH Server (sshd)' `
          -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22
      register: firewall_rule
      failed_when:
        - firewall_rule.rc != 0
        - "'already exists' not in firewall_rule.stderr"
      changed_when: "'already exists' not in firewall_rule.stderr"

    - name: Set default shell to PowerShell
      ansible.windows.win_shell: |
        New-ItemProperty -Path "HKLM:\SOFTWARE\OpenSSH" -Name DefaultShell `
          -Value "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -PropertyType String -Force
      register: default_shell

    - name: Configure SSH to use authorized_keys for non-admin users
      ansible.windows.win_shell: |
        $sshdConfigPath = "$env:ProgramData\ssh\sshd_config"
        $content = Get-Content $sshdConfigPath

        # Comment out the administrators_authorized_keys lines if they exist
        $content = $content -replace '^(Match Group administrators)', '#$1'
        $content = $content -replace '^(\s+AuthorizedKeysFile\s+__PROGRAMDATA__)', '#$1'

        # Ensure PubkeyAuthentication is enabled
        if ($content -notmatch 'PubkeyAuthentication\s+yes') {
            $content += "`nPubkeyAuthentication yes"
        }

        $content | Set-Content $sshdConfigPath
      register: sshd_config

    - name: Restart SSH service to apply configuration
      ansible.windows.win_service:
        name: sshd
        state: restarted
      when: sshd_config.changed

    - name: Display configuration complete message
      ansible.builtin.debug:
        msg:
          - "OpenSSH Server is now configured"
          - "SSH service is running"
          - "Firewall rule is configured"
          - "Default shell is set to PowerShell"
          - "SSH configured to use authorized_keys"
