---
- name: Verify server4 tags
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Get server4 information
      azure.azcollection.azure_rm_virtualmachine_info:
        resource_group: "ansible-{{ ansible_user_id }}"
        name: server4
      register: vm_info

    - name: Display all tags on server4
      ansible.builtin.debug:
        msg: "server4 tags: {{ vm_info.vms[0].tags }}"
