---
- name: Test Windows SSH Connection
  hosts: windows
  gather_facts: false

  tasks:
    - name: Test connection with ping
      ansible.builtin.win_ping:

    - name: Display success message
      ansible.builtin.debug:
        msg: "Successfully connected to {{ inventory_hostname }} via SSH"

    - name: Run PowerShell command via SSH
      ansible.windows.win_shell: |
        $PSVersionTable.PSVersion | Select-Object Major, Minor, Build
      register: ps_version

    - name: Display PowerShell version
      ansible.builtin.debug:
        msg: "{{ ps_version.stdout_lines }}"
