---
- name: Gather Windows Facts via SSH
  hosts: windows
  gather_facts: true

  tasks:
    - name: Display connection method
      ansible.builtin.debug:
        msg: "Connected via: {{ ansible_connection }}"

    - name: Display OS information
      ansible.builtin.debug:
        msg:
          - "OS: {{ ansible_os_family }}"
          - "OS Name: {{ ansible_distribution }}"
          - "Hostname: {{ ansible_hostname }}"
          - "Architecture: {{ ansible_architecture }}"

    - name: Display network information
      ansible.builtin.debug:
        msg:
          - "IP Addresses: {{ ansible_ip_addresses }}"

    - name: Get disk information via SSH
      ansible.windows.win_shell: |
        Get-PSDrive -PSProvider FileSystem |
        Where-Object {$_.Used -ne $null} |
        Format-Table Name, @{n='Used(GB)';e={[math]::Round($_.Used/1GB,2)}},
                          @{n='Free(GB)';e={[math]::Round($_.Free/1GB,2)}} -AutoSize |
        Out-String
      register: disk_info

    - name: Display disk information
      ansible.builtin.debug:
        msg: "{{ disk_info.stdout_lines }}"
