
---
- name: Execute PowerShell Commands
  hosts: windows
  gather_facts: false

  tasks:
    - name: Get current date and time
      ansible.windows.win_shell: Get-Date -Format "yyyy-MM-dd HH:mm:ss"
      register: current_time

    - name: Display current time
      ansible.builtin.debug:
        msg: "Windows Server Time: {{ current_time.stdout | trim }}"

    - name: Get running services
      ansible.windows.win_shell: |
        Get-Service | Where-Object {$_.Status -eq 'Running'} |
        Select-Object -First 5 Name, DisplayName, Status |
        Format-Table -AutoSize | Out-String
      register: services

    - name: Display running services
      ansible.builtin.debug:
        msg: "{{ services.stdout_lines }}"

    - name: Get system uptime
      ansible.windows.win_shell: |
        $os = Get-CimInstance Win32_OperatingSystem
        $uptime = (Get-Date) - $os.LastBootUpTime
        "System has been up for: {0} days, {1} hours, {2} minutes" -f $uptime.Days, $uptime.Hours, $uptime.Minutes
      register: uptime

    - name: Display uptime
      ansible.builtin.debug:
        msg: "{{ uptime.stdout | trim }}"

    - name: Check disk space
      ansible.windows.win_shell: |
        Get-PSDrive -PSProvider FileSystem |
        Where-Object {$_.Used -ne $null} |
        Select-Object Name, @{Name='Used(GB)';Expression={[math]::Round($_.Used/1GB,2)}},
                           @{Name='Free(GB)';Expression={[math]::Round($_.Free/1GB,2)}} |
        Format-Table -AutoSize | Out-String
      register: disk_space

    - name: Display disk space
      ansible.builtin.debug:
        msg: "{{ disk_space.stdout_lines }}"