---
- name: Copy SSH Public Key to Windows Host
  hosts: windows
  gather_facts: false

  vars:
    ssh_key_file: "~/.ssh/windows_rsa.pub"

  tasks:
    - name: Read SSH public key from local file
      ansible.builtin.slurp:
        src: "{{ ssh_key_file }}"
      register: ssh_public_key
      delegate_to: localhost

    - name: Create .ssh directory in user's home
      ansible.windows.win_file:
        path: "C:\\Users\\{{ ansible_user }}\\.ssh"
        state: directory

    - name: Create authorized_keys file with public key
      ansible.windows.win_copy:
        content: "{{ ssh_public_key.content | b64decode }}"
        dest: "C:\\Users\\{{ ansible_user }}\\.ssh\\authorized_keys"

    - name: Set correct permissions on authorized_keys
      ansible.windows.win_shell: |
        icacls "C:\Users\{{ ansible_user }}\.ssh\authorized_keys" /inheritance:r
        icacls "C:\Users\{{ ansible_user }}\.ssh\authorized_keys" /grant "{{ ansible_user }}:F"
        icacls "C:\Users\{{ ansible_user }}\.ssh\authorized_keys" /grant "SYSTEM:F"

    - name: Display success message
      ansible.builtin.debug:
        msg: "SSH public key copied successfully to {{ ansible_user }}'s authorized_keys"
